-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeJIAAuZ9eVmBbtJa500kPknsbTrssagbRjsG9uPlVcagCgYIKoZIzj0DAQehRANCAASbFlZoIbooBqBp7SCOl0yMq+rhLFLXmWAWnShAmI874bVYFpHDXbKUfNI1eDS5vBnztPlIoJ1IfYyEfLNpMTUO
-----END PRIVATE KEY-----