-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyYdyYW/SVg3DU5P4Dy2P4OYetxsXT0hI2EQGlbFuji6gCgYIKoZIzj0DAQehRANCAARf3uejwCsijNjqcRTPLAcDoB3LucaKHNpYUmSClnNVCzeLGbEjCaVJC47beh+pNQkhHv8zBPIyQ/xJt0uH7pR5
-----END PRIVATE KEY-----